import { Container } from "@chakra-ui/react";
import { Header } from "@components/Header";
import { RepositoryList } from "@components/RepositoryList";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Container maxW="4xl">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <RepositoryList />
      </Container>
    </>
  );
};

export default Home;
